Repository LilithHafner/Chairmarks.jl, pull requests merged in 2024-09, with the labels that each got.

#110 Fix time conversion in BenchmarkTools comparison
  docs/src/migration.md
Labels: documentation, bugfix

#105 Handle seconds=Inf and very high seconds args gracefully (unbounded runtime if samples and evals are specified, otherwise throw)
  src/benchmarking.jl
  test/runtests.jl
Labels: bugfix

#123 Refer to @be in why.md not @b which directs to @be
  docs/src/why.md
Labels: documentation

#125 Update truthful section based on the use of `Base.donotdelete`
  docs/src/why.md
Labels: documentation

#126 Update doc typo in Chairmarks.jl
  src/Chairmarks.jl
Labels: documentation
